# Generated by Django 6.0.7 on 2026-08-05 18:19

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_code', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('running_hrs', models.FloatField(default=0.0)),
                ('kva', models.IntegerField(default=0)),
                ('year_of_manufacture', models.IntegerField(blank=True, null=True)),
                ('service_yr_in_koc', models.IntegerField(blank=True, null=True)),
                ('from_location', models.CharField(blank=True, max_length=100, null=True)),
                ('to_location', models.CharField(blank=True, max_length=100, null=True)),
                ('field', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.CharField(blank=True, max_length=100, null=True)),
                ('movement_date', models.DateField(blank=True, null=True)),
                ('purpose', models.CharField(blank=True, max_length=255, null=True)),
                ('service_technician', models.CharField(blank=True, max_length=100, null=True)),
                ('supervisor', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_comment', models.TextField(blank=True, null=True)),
                ('cycle_start_date', models.DateField(blank=True, default=datetime.date.today, null=True)),
            ],
            options={
                'db_table': 'generator_assets',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WarehousePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Shelf, bin, or aisle location', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('compatibility_asset', models.CharField(help_text='Compatible generator or equipment', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse Part',
                'verbose_name_plural': 'Warehouse Parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratorPMServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=50)),
                ('service_date', models.DateField(default=datetime.date.today)),
                ('running_hrs_at_service', models.FloatField()),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('work_order_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_logs', to='myapp.asset')),
            ],
        ),
        migrations.CreateModel(
            name='PartIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_logs', to='myapp.warehousepart')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('service_type', models.CharField(blank=True, max_length=50)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('resolved_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='myapp.asset')),
            ],
        ),
    ]
