# Generated by Django 6.0.7 on 2026-08-04 18:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehousePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=150)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('supplier', models.CharField(max_length=150)),
                ('location', models.CharField(help_text='Shelf, bin, or aisle location', max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('compatibility_asset', models.CharField(help_text='Compatible generator or equipment', max_length=150)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('date_received', models.DateField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Warehouse Part',
                'verbose_name_plural': 'Warehouse Parts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='asset',
            options={'managed': False},
        ),
    ]
