# Generated by Django 6.0.7 on 2026-08-05 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_warehousepart_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='asset',
            table='generator_assets',
        ),
        migrations.CreateModel(
            name='PartIssueLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issued_quantity', models.IntegerField()),
                ('destination', models.CharField(max_length=100)),
                ('issued_by', models.CharField(blank=True, max_length=100)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue_logs', to='myapp.warehousepart')),
            ],
        ),
    ]
