# Generated by Django 6.0.7 on 2026-08-05 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_asset_table_partissuelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_code', models.CharField(max_length=50, unique=True)),
                ('serial_number', models.CharField(max_length=100)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('running_hrs', models.IntegerField(default=0)),
                ('pm_interval_hrs', models.IntegerField(default=250)),
                ('last_pm_running_hrs', models.IntegerField(default=0)),
                ('next_pm_due_hrs', models.IntegerField(default=250)),
                ('last_pm_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorPMServiceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('A_SERVICE', 'Service A (Minor - Oil & Filters)'), ('B_SERVICE', 'Service B (Medium - Fuel/Air Filters)'), ('C_SERVICE', 'Service C (Major Overhaul)')], default='A_SERVICE', max_length=20)),
                ('service_date', models.DateField()),
                ('running_hrs_at_service', models.IntegerField()),
                ('technician', models.CharField(blank=True, max_length=100)),
                ('work_order_number', models.CharField(blank=True, max_length=50)),
                ('parts_used', models.TextField(blank=True, help_text='e.g. Oil Filter x1, Fuel Filter x2')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_logs', to='myapp.generatorasset')),
            ],
        ),
    ]
