# Generated by Django 6.0.7 on 2026-08-05 16:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_generatorasset_generatorpmservicelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_code', models.CharField(max_length=50, unique=True)),
                ('model', models.CharField(blank=True, max_length=50)),
                ('running_hrs', models.IntegerField(default=0)),
                ('cycle_start_date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.RemoveField(
            model_name='generatorpmservicelog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='generatorpmservicelog',
            name='parts_used',
        ),
        migrations.AlterField(
            model_name='generatorpmservicelog',
            name='service_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='generatorpmservicelog',
            name='service_type',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='generatorpmservicelog',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_logs', to='myapp.generator'),
        ),
        migrations.DeleteModel(
            name='GeneratorAsset',
        ),
    ]
