# Generated by Django 6.0.7 on 2026-08-06 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeavePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/')),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('oracle_id', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(max_length=100)),
                ('nationality', models.CharField(blank=True, max_length=80, null=True)),
                ('company_mobile_no', models.CharField(blank=True, max_length=20, null=True)),
                ('project', models.CharField(choices=[('GENSET_WORKSHOP', 'Genset Workshop'), ('GENSET_FIELD', 'Genset Field'), ('WAFULA', 'Wafula')], max_length=50)),
                ('department', models.CharField(choices=[('GENSET_WORKSHOP', 'Genset Workshop'), ('GENSET_FIELD', 'Genset Field')], max_length=50)),
                ('civil_id_no', models.CharField(blank=True, max_length=50, null=True)),
                ('civil_id_issue_date', models.DateField(blank=True, null=True)),
                ('civil_id_expire_date', models.DateField(blank=True, null=True)),
                ('passport_no', models.CharField(blank=True, max_length=50, null=True)),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expire_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(help_text='Employment Date')),
                ('planned_leave_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee Leave Plan',
                'verbose_name_plural': 'Employee Leave Plans',
                'ordering': ['employee_name'],
            },
        ),
        migrations.AlterField(
            model_name='generatorpmservicelog',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_logs', to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='generator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='myapp.asset'),
        ),
        migrations.AlterField(
            model_name='generatorpmservicelog',
            name='running_hrs_at_service',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Generator',
        ),
    ]
