# Generated by Django 6.0.7 on 2026-08-06 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_employeeleaveplan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=150)),
                ('employee_id', models.CharField(max_length=50)),
                ('civil_id_no', models.CharField(max_length=50, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100, null=True)),
                ('designation_on_card', models.CharField(max_length=150)),
                ('project_sponsor', models.CharField(blank=True, max_length=150, null=True)),
                ('card_serial_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expire_date', models.DateField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active / Valid'), ('IN_PROGRESS', 'Renewal in Progress'), ('EXPIRING_SOON', 'Expiring Soon'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('card_document', models.FileField(blank=True, null=True, upload_to='resident_cards/')),
                ('renewal_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['expire_date'],
            },
        ),
    ]
