# Generated by Django 6.0.7 on 2026-08-06 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_residentcard'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrderReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_wo_number', models.CharField(help_text='Work Order ID from Dynamics CRM', max_length=100, unique=True)),
                ('customer_or_site', models.CharField(help_text='Client Name or Site Location', max_length=150)),
                ('equipment_asset_id', models.CharField(blank=True, help_text='Generator / Asset ID', max_length=100, null=True)),
                ('crm_planned_parts', models.TextField(blank=True, help_text='Parts scope specified in Dynamics', null=True)),
                ('service_book_serial_no', models.CharField(blank=True, help_text='Serial number from physical paper book page', max_length=100, null=True)),
                ('technician_name', models.CharField(blank=True, max_length=150, null=True)),
                ('service_type', models.CharField(choices=[('PREVENTATIVE', 'Preventative Maintenance'), ('CORRECTIVE', 'Corrective / Breakdown Repair'), ('INSPECTION', 'Inspection & Testing'), ('OVERHAUL', 'Major Overhaul'), ('PART_REPLACEMENT', 'Service Parts Replacement')], default='PREVENTATIVE', max_length=50)),
                ('actual_parts_used', models.TextField(blank=True, help_text='Actual parts written on the paper slip', null=True)),
                ('service_date', models.DateField(blank=True, null=True)),
                ('reconciliation_status', models.CharField(choices=[('MATCHED', 'Fully Matched'), ('PENDING_PAPER', 'Pending Paper Slip'), ('DISCREPANCY', 'Parts / Scope Discrepancy')], default='PENDING_PAPER', max_length=30)),
                ('discrepancy_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
