# Generated by Django 6.0.7 on 2026-08-06 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_workorderreconciliation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeleaveplan',
            options={},
        ),
        migrations.RemoveField(
            model_name='employeeleaveplan',
            name='civil_id_issue_date',
        ),
        migrations.RemoveField(
            model_name='employeeleaveplan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='employeeleaveplan',
            name='passport_issue_date',
        ),
        migrations.RemoveField(
            model_name='employeeleaveplan',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='civil_id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='company_mobile_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='department',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='designation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='employee_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='employee_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='nationality',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='oracle_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='passport_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleaveplan',
            name='project',
            field=models.CharField(max_length=100),
        ),
    ]
