# Generated by Django 6.0.7 on 2026-08-06 18:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_employeeleaveplan_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleaveplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeleaveplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
