# Generated by Django 6.0.7 on 2026-08-12 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_employeeleaveplan_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratorAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='GeneratorDiagnostics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_running', models.BooleanField(default=False)),
                ('last_command', models.CharField(default='Idle', max_length=50)),
                ('command_initiated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('oil_pressure', models.FloatField(blank=True, help_text='Bar or PSI', null=True)),
                ('coolant_temp', models.FloatField(blank=True, help_text='in °C', null=True)),
                ('battery_voltage', models.FloatField(blank=True, help_text='in Volts', null=True)),
                ('fuel_level', models.FloatField(blank=True, help_text='Percentage %', null=True)),
                ('warning_status', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning (Action Required)'), ('CRITICAL', 'Critical (Trip Imminent)')], default='NORMAL', max_length=20)),
                ('warning_message', models.TextField(blank=True, null=True)),
                ('fault_code', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=10)),
                ('symptoms', models.TextField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, null=True)),
                ('corrective_action', models.TextField(blank=True, null=True)),
                ('technician', models.CharField(blank=True, max_length=100, null=True)),
                ('resolved', models.BooleanField(default=False)),
                ('generator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostics_logs', to='myapp.generatorasset')),
            ],
        ),
    ]
